In [11]:
import numpy as np
import pandas as pd

#Read in new board game data
popular_board_game_df = pd.read_csv('./popular_board_game.csv')
popular_board_game_df['player_type'] = np.where(popular_board_game_df['min_players']== 1, 'support solo', 'not support solo')

#Create new dataframe containing data for 1b
output_df = pd.DataFrame()
output_df['category'] = popular_board_game_df['category'].unique()

In [6]:
output_df['total_num_game_solo'] = popular_board_game_df.loc

     category
0    Economic
1    Fighting
2   Deduction
3    Bluffing
4  Party Game

In [12]:
popular_board_game_df

,name,category,playtime,playtime_num,avg_rating,num_ratings,min_players,player_type
0,Agricola,Economic,>90,150,7.98857,61557,1,support solo
1,Puerto Rico,Economic,>90,150,8.03590,61157,3,not support solo
2,Small World,Fighting,"(60, 90]",80,7.29949,59211,2,not support solo
3,Codenames,Deduction,<=30,15,7.71148,62563,2,not support solo
4,Power Grid,Economic,>90,120,7.89004,54420,2,not support solo
...,...,...,...,...,...,...,...,...
239,Decrypto,Deduction,"(30, 60]",45,7.80797,9659,3,not support solo
240,Agricola (Revised Edition),Economic,>90,120,8.12485,7982,1,support solo
241,Chronicles of Crime,Deduction,"(60, 90]",90,8.03759,11684,1,support solo
242,Just One,Party Game,<=30,20,7.57741,8979,3,not support solo
243,The Lord of the Rings: Journeys in Middle-earth,Fighting,>90,120,8.40100,6688,1,support solo

In [20]:
popular_board_game_df.groupby(['category','player_type']).count()['name'].index

MultiIndex([(  'Bluffing', 'not support solo'),
            ( 'Deduction', 'not support solo'),
            ( 'Deduction',     'support solo'),
            (  'Economic', 'not support solo'),
            (  'Economic',     'support solo'),
            (  'Fighting', 'not support solo'),
            (  'Fighting',     'support solo'),
            ('Party Game', 'not support solo'),
            ('Party Game',     'support solo')],
           names=['category', 'player_type'])